### PR TITLE
Removed: Incorrect flag in gradle.properties #91

### PR DESCRIPTION
**Pull request by NaincyKumariKnoldus**
Hey ! I have made the changes in gradle.properties file. Please review my PR.
Thanks!
#91

### CODE REVIEW

**Comment by theapache64** [comment]
Hi @NaincyKumariKnoldus 
Can you please explain how this is incorrect?

**Comment by NaincyKumariKnoldus** [comment]
> Hi @NaincyKumariKnoldus Can you please explain how this is incorrect?

The error was coming of Unable to start the daemon process. This problem might be caused by incorrect configuration of the daemon.
And it was telling Unrecognized VM option 'MaxPermSize=1024m'

So, when I removed this incorrect flag -XX:MaxPermSize=1024m from gradle.properties builds correctly.

**Comment by theapache64** [comment]
@NaincyKumariKnoldus Can you share your
- OS details,
- command you tried
- stacktrace it produced?

**Comment by theapache64** [comment]
Closing due to inactivity. Feel free reopen

**Pull request closed without merging**
